/* tslint:disable */
/* eslint-disable */
/**
 * Giant Robots
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GiantRobot
 */
export interface GiantRobot {
    /**
     * 
     * @type {string}
     * @memberof GiantRobot
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GiantRobot
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GiantRobot
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof GiantRobot
     */
    weight: number;
}

export function GiantRobotFromJSON(json: any): GiantRobot {
    return GiantRobotFromJSONTyped(json, false);
}

export function GiantRobotFromJSONTyped(json: any, ignoreDiscriminator: boolean): GiantRobot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'height': json['height'],
        'weight': json['weight'],
    };
}

export function GiantRobotToJSON(value?: GiantRobot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'height': value.height,
        'weight': value.weight,
    };
}


